use_frameworks!

platform :ios, '11.0'

target 'crowdplaysdk_Example' do
  pod 'crowdplaysdk', :path => '../'

  target 'crowdplaysdk_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.2.0'
    pod 'Nimble', '~> 9.2'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Nimble-Snapshots' , '~> 9.2'
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
     target.build_configurations.each do |config|
       config.build_settings['ENABLE_BITCODE'] = 'YES'
       config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
     end
  end
end