use_frameworks!

platform :ios, '10.0'

target 'crowdplaysdk_Example' do
  pod 'crowdplaysdk', :path => '../'

  target 'crowdplaysdk_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.2.0'
    pod 'Nimble', '~> 9.2'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Nimble-Snapshots' , '~> 9.2'
  end
end
